export { IndexPage } from './indexPage/IndexPage'
export { ProfilePage } from './profilePage/ProfilePage'
export { AuthPage } from './authPage/AuthPage'
export { ProductsPage } from './productsPage/ProductsPage'
export { FavoritesPage } from './favoritesPage/FavoritesPage'
export { ProductPage } from './productPage/ProductPage'
export { AdminPage } from './adminPage/AdminPage'